server:
  port: 8001
#  servlet:
#    context-path: /cloud-payment-nacos-service
spring:
  application:
    name: cloud-payment-nacos-service
    cloud:
      nacos:
        discovery:
          server-addr: localhost:8848
management:
  endpoints:
    web:
      exposure:
        include: '*'



