server:
  port: 8001
spring:
  application:
    name: cloud-payment-nacos-service8001
    cloud:
      nacos:
        discovery:
          server-addr: localhost:8848
#management:
#  endpoints:
#    web:
#      exposure:
#        include: *



