server:
  port: 8021
spring:
  application:
    name: seata-order-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: "b12c263b-956c-45b3-9d20-14ec0bebbd0e"
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://127.0.0.1:3306/seata_order?useCharactorEncoding=utf-8&useSSL=false&serverTimezone=UTC
#    username: root
#    password: root

seata:
  enabled: true
  application-id: seata-server
  tx-service-group: my_seata_group
  data-source-proxy-mode: AT
  enable-auto-data-source-proxy: true
  registry:
    type: nacos
    nacos:
      server-addr: localhost:8848
      application: seata-server
      group: SEATA_GROUP
      namespace: "b12c263b-956c-45b3-9d20-14ec0bebbd0e"
      username: nacos
      password: nacos
  service:
    vgroup-mapping:
      my_seata_group : default
    enable-degrade: false
    disable-global-transaction: false
  config: #配置中心
    type: nacos
    nacos:
      server-addr: 127.0.0.1:8848
      group: SEATA_GROUP
      namespace: "b12c263b-956c-45b3-9d20-14ec0bebbd0e"
      username: "nacos"
      password: "nacos"
  client:
    undo:
      log-table: undo_log
      data-validation: true
      only-care-update-columns: true
      log-serialization: fastjson


feign:
  hystrix:
    enabled: false
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml