server:
  port: 8401
spring:
  application:
    name: cloud-sentinel-server
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos注册地址
    sentinel:
      transport:
        dashboard: localhost:8080 #sentinel地址
        port: 8719 #默认端口
      web-context-unify: false  # 限流 链路 配置