#server：
# port： 8081
#spring.application.name=service-consumer
#spring.cloud.nacos.discovery.server-addr=127.0.0.1:8848
server:
  port: 8081
spring:
  application:
    name: cloud-payment-nacos-consumer8081
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848

service-url:
  nacos-user-service: http://cloud-payment-nacos-service